import javax.swing.*;
import java.awt.*;

public class ChessBoard {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		JFrame theGUI = new JFrame();
		theGUI.setTitle("Chess Board");
		theGUI.setSize(500, 500);
		theGUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		JPanel panel = new JPanel();
		panel.setBackground(Color.black);
		JPanel panel2 = new JPanel();
		panel2.setBackground(Color.white);
		JPanel panel3 = new JPanel();
		panel3.setBackground(Color.black);
		JPanel panel4 = new JPanel();
		panel4.setBackground(Color.white);
		JPanel panel5 = new JPanel();
		panel5.setBackground(Color.black);
		JPanel panel6 = new JPanel();
		panel6.setBackground(Color.white);
		JPanel panel7 = new JPanel();
		panel7.setBackground(Color.black);
		JPanel panel8 = new JPanel();
		panel8.setBackground(Color.white);
		JPanel panel9 = new JPanel();
		panel9.setBackground(Color.white);
		JPanel panel10 = new JPanel();
		panel10.setBackground(Color.black);
		JPanel panel11 = new JPanel();
		panel11.setBackground(Color.white);
		JPanel panel12 = new JPanel();
		panel12.setBackground(Color.black);
		JPanel panel13 = new JPanel();
		panel13.setBackground(Color.white);
		JPanel panel14 = new JPanel();
		panel14.setBackground(Color.black);
		JPanel panel15 = new JPanel();
		panel15.setBackground(Color.white);
		JPanel panel16 = new JPanel();
		panel16.setBackground(Color.black);
		JPanel panel17 = new JPanel();
		panel17.setBackground(Color.black);
		JPanel panel18 = new JPanel();
		panel18.setBackground(Color.white);
		JPanel panel19 = new JPanel();
		panel19.setBackground(Color.black);
		JPanel panel20 = new JPanel();
		panel20.setBackground(Color.white);
		JPanel panel21 = new JPanel();
		panel21.setBackground(Color.black);
		JPanel panel22 = new JPanel();
		panel22.setBackground(Color.white);
		JPanel panel23 = new JPanel();
		panel23.setBackground(Color.black);
		JPanel panel24 = new JPanel();
		panel24.setBackground(Color.white);
		JPanel pain9 = new JPanel();
		pain9.setBackground(Color.white);
		JPanel pain10 = new JPanel();
		pain10.setBackground(Color.black);
		JPanel pain11 = new JPanel();
		pain11.setBackground(Color.white);
		JPanel pain12 = new JPanel();
		pain12.setBackground(Color.black);
		JPanel pain13 = new JPanel();
		pain13.setBackground(Color.white);
		JPanel pain14 = new JPanel();
		pain14.setBackground(Color.black);
		JPanel pain15 = new JPanel();
		pain15.setBackground(Color.white);
		JPanel pain16 = new JPanel();
		pain16.setBackground(Color.black);
		JPanel pain = new JPanel();
		pain.setBackground(Color.black);
		JPanel pain2 = new JPanel();
		pain2.setBackground(Color.white);
		JPanel pain3 = new JPanel();
		pain3.setBackground(Color.black);
		JPanel pain4 = new JPanel();
		pain4.setBackground(Color.white);
		JPanel pain5 = new JPanel();
		pain5.setBackground(Color.black);
		JPanel pain6 = new JPanel();
		pain6.setBackground(Color.white);
		JPanel pain7 = new JPanel();
		pain7.setBackground(Color.black);
		JPanel pain8 = new JPanel();
		pain8.setBackground(Color.white);
		JPanel pain17 = new JPanel();
		pain17.setBackground(Color.black);
		JPanel pain18 = new JPanel();
		pain18.setBackground(Color.white);
		JPanel pain19 = new JPanel();
		pain19.setBackground(Color.black);
		JPanel pain20 = new JPanel();
		pain20.setBackground(Color.white);
		JPanel pain21 = new JPanel();
		pain21.setBackground(Color.black);
		JPanel pain22 = new JPanel();
		pain22.setBackground(Color.white);
		JPanel pain23 = new JPanel();
		pain23.setBackground(Color.black);
		JPanel pain24 = new JPanel();
		pain24.setBackground(Color.white);
		JPanel panell9 = new JPanel();
		panell9.setBackground(Color.white);
		JPanel panell10 = new JPanel();
		panell10.setBackground(Color.black);
		JPanel panell11 = new JPanel();
		panell11.setBackground(Color.white);
		JPanel panell12 = new JPanel();
		panell12.setBackground(Color.black);
		JPanel panell13 = new JPanel();
		panell13.setBackground(Color.white);
		JPanel panell14 = new JPanel();
		panell14.setBackground(Color.black);
		JPanel panell15 = new JPanel();
		panell15.setBackground(Color.white);
		JPanel panell16 = new JPanel();
		panell16.setBackground(Color.black);
		JPanel panell = new JPanel();
		panell.setBackground(Color.white);
		JPanel panell2 = new JPanel();
		panell2.setBackground(Color.black);
		JPanel panell3 = new JPanel();
		panell3.setBackground(Color.white);
		JPanel panell4 = new JPanel();
		panell4.setBackground(Color.black);
		JPanel panell5 = new JPanel();
		panell5.setBackground(Color.white);
		JPanel panell6 = new JPanel();
		panell6.setBackground(Color.black);
		JPanel panell7 = new JPanel();
		panell7.setBackground(Color.white);
		JPanel panell8 = new JPanel();
		panell8.setBackground(Color.black);
		Container pane = theGUI.getContentPane();
		pane.setLayout(new GridLayout(8, 8));
		pane.add(panel);
		pane.add(panel2);
		pane.add(panel3);
		pane.add(panel4);
		pane.add(panel5);
		pane.add(panel6);
		pane.add(panel7);
		pane.add(panel8); //s
		pane.add(panel9);
		pane.add(panel10);
		pane.add(panel11);
		pane.add(panel12);
		pane.add(panel13);
		pane.add(panel14);
		pane.add(panel15);
		pane.add(panel16); //s
		pane.add(panel17);
		pane.add(panel18);
		pane.add(panel19);
		pane.add(panel20);
		pane.add(panel21);
		pane.add(panel22);
		pane.add(panel23);
		pane.add(panel24); //s
		pane.add(pain9);
		pane.add(pain10);
		pane.add(pain11);
		pane.add(pain12);
		pane.add(pain13);
		pane.add(pain14);
		pane.add(pain15);
		pane.add(pain16); //s
		pane.add(pain);
		pane.add(pain2);
		pane.add(pain3);
		pane.add(pain4);
		pane.add(pain5);
		pane.add(pain6);
		pane.add(pain7);
		pane.add(pain8); //s
		pane.add(panell9);
		pane.add(panell10);
		pane.add(panell11);
		pane.add(panell12);
		pane.add(panell13);
		pane.add(panell14);
		pane.add(panell15);
		pane.add(panell16); //s
		pane.add(pain17);
		pane.add(pain18);
		pane.add(pain19);
		pane.add(pain20);
		pane.add(pain21);
		pane.add(pain22);
		pane.add(pain23);
		pane.add(pain24); //s
		pane.add(panell);
		pane.add(panell2);
		pane.add(panell3);
		pane.add(panell4);
		pane.add(panell5);
		pane.add(panell6);
		pane.add(panell7);
		pane.add(panell8); //s
		theGUI.setVisible(true);
	}

}
